- debug:
    msg: "Managing local user account {{ ivar_user }}"
  tags:
    - debug

- name: Creating local user account
  user:
    name: "{{ ivar_user }}"
    shell: /bin/bash

#-------------------------------------------------------------------------------

- name: Managing group memberships
  user:
    name: "{{ ivar_user }}"
    groups: "{{ item }}"
    append: yes
  with_items: "{{ ivar_metadata.get('groups', []) }}"

- name: Getting current group memberships
  command: "groups {{ ivar_user }}"
  register: current_group_memberships
  changed_when: False

- debug: var=current_group_memberships
  tags:
    - debug

- set_fact:
    current_group_list: "{{ current_group_memberships.stdout.replace(ivar_user+' : ', '').split(' ') }}"

- debug: var=current_group_list
  tags:
    - debug

- name: Removing extra group memberships
  command: "deluser {{ ivar_user }} {{ item }}"
  loop: "{{ current_group_list }}"
  when: item != ivar_user and item not in ivar_metadata.get('groups', [])

#-------------------------------------------------------------------------------

- name: Managing home directory permissions
  file:
    path: "/home/{{ ivar_user }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0750
    state: directory

#-------------------------------------------------------------------------------

- name: Managing .ssh directory for local user account
  file:
    path: "/home/{{ ivar_user }}/.ssh"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0700
    state: directory

- name: Managing SSH keys for local user account
  template:
    src: authorized_keys.j2
    dest: "/home/{{ ivar_user }}/.ssh/authorized_keys"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
    mode: 0644
    backup: yes

#-------------------------------------------------------------------------------

- name: Manage user home subdirectories
  file:
    path: "/home/{{ ivar_user }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
  with_filetree:
    - "user_files/{{ ivar_user }}/"
    - "user_files/all/"
  when: item.state == 'directory'

- name: Manage user home files
  template:
    src: "{{ item.src }}"
    dest: "/home/{{ ivar_user }}/{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ ivar_user }}"
    group: "{{ ivar_user }}"
  with_filetree:
    - "user_files/{{ ivar_user }}/"
    - "user_files/all/"
  when: item.state == 'file'
